### ISSUE TITLE
Change Title to Avoid Appearing Like the Measurement is Made

### ISSUE THREAD

**Issue by farr** [farr/PISNLineCosmography#10]
This from Shoemaker:

> Will, I think a change in the title is certainly needed; it will be misunderstood by most that you are announcing that such a determination has already been made. Potential for, A Path for, Future percent-level….

**Comment by farr** [comment]
From amongst the options, I like "A Future...," so I'm going to change that now, but leave the issue open for comment.

**Comment by deholz** [comment]
Precision cosmology from gravitational-wave measurements of features in the mass distribution of black holes
Precision cosmology from future gravitational-wave measurements of features in the mass distribution of black holes
A Future Percent-Level Measurement of the Hubble Expansion at Redshift 0.8 With  Gravitational Waves (replace Hubble Parameter->Hubble Expansion to make it clear we're not measuring H0?)

**Comment by farr** [comment]
How about 

A Future Percent-Level Measurement of the Hubble Expansion at Redshift 0.8 with Advanced LIGO

Pros:

* Makes clear that this measurement is coming soon

Cons:

* We also talk about 3G, Virgo, LIGO India, Kagra, etc.  Advanced LIGO is not a fundamental physical concept; gravitational waves are.

**Comment by farr** [comment]
Closing this for now.
