### ISSUE TITLE
Discuss Spera & Mapelli MMax(z)

### ISSUE THREAD

**Issue by farr** [farr/PISNLineCosmography#2]
- [x] Motivate tapered power law
- [x] Cluster formation could give larger MMax
- [x] How much does it evolve in redshift.
- [x] Note that H(z) uncertainty gets better with a sharp cutoff.

**Comment by mfishbach** [comment]
http://adsabs.harvard.edu/abs/2017MNRAS.472.2422M

**Comment by farr** [comment]
Decided to leave out the cluster discussion for space considerations; can put it back of the referee or you folks think it's important.
