### ISSUE TITLE
Citations for Current Measurements of w

### ISSUE THREAD

**Issue by farr** [farr/PISNLineCosmography#9]
See the blue "CITE" following the text "...other constraints on w".  Need citations that show that a ~10% constraint on w would be competitive with existing measurements (if that is true), and point to existing measurements in any case.

**Comment by deholz** [comment]
I put in the most recent reference I could find on this (DES joint probe PRL).

**Comment by farr** [comment]
Great---thanks for taking care of that!

**Comment by farr** [comment]
Also: that paper is *also* an Abbot, et al.?  AYFKM?
